In [1]:
if(!require("dplyr"))install.packages(dplyr)

Loading required package: dplyr

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



In [2]:
getwd()

[1] "/Users/shiny/rnote/MachineLearning/Movie Lens"

In [3]:
movieLenz <- read.csv(file="./ml-100k/u.data",sep="\t",header=FALSE)

In [4]:
str(movieLenz)

'data.frame':	100000 obs. of  4 variables:
 $ V1: int  196 186 22 244 166 298 115 253 305 6 ...
 $ V2: int  242 302 377 51 346 474 265 465 451 86 ...
 $ V3: int  3 3 1 2 1 4 2 5 3 3 ...
 $ V4: int  881250949 891717742 878887116 880606923 886397596 884182806 881171488 891628467 886324817 883603013 ...


In [5]:
colnames(movieLenz) <- c("id","movie","rating","create_date_time")

In [6]:
movieLenz$rating <- as.double(movieLenz$rating)

In [7]:
str(movieLenz)

'data.frame':	100000 obs. of  4 variables:
 $ id              : int  196 186 22 244 166 298 115 253 305 6 ...
 $ movie           : int  242 302 377 51 346 474 265 465 451 86 ...
 $ rating          : num  3 3 1 2 1 4 2 5 3 3 ...
 $ create_date_time: int  881250949 891717742 878887116 880606923 886397596 884182806 881171488 891628467 886324817 883603013 ...


In [8]:
library(dplyr)

In [9]:
movie.df <- tbl_df(movieLenz)

In [10]:
row_names <- summarise(group_by(movie.df,id)[1], count = n())[1]

In [11]:
row_vec <- row_names$id

In [12]:
length(row_vec)

[1] 943

In [13]:
col_names <- summarise(group_by(movie.df,movie)[2], count = n())[1]

In [14]:
col_vec <- col_names$movie

In [15]:
length(col_vec)

[1] 1682

In [16]:
rating.df <-matrix(0.0,nrow=length(row_vec), ncol=length(col_vec))

In [17]:
str(rating.df)

 num [1:943, 1:1682] 0 0 0 0 0 0 0 0 0 0 ...


In [18]:
df <- as.data.frame(arrange(movie.df,id))

In [19]:
str(df)

'data.frame':	100000 obs. of  4 variables:
 $ id              : int  1 1 1 1 1 1 1 1 1 1 ...
 $ movie           : int  61 189 33 160 20 202 171 265 155 117 ...
 $ rating          : num  4 3 4 4 4 5 5 4 2 3 ...
 $ create_date_time: int  878542420 888732928 878542699 875072547 887431883 875072442 889751711 878542441 878542201 874965739 ...


In [20]:
for ( i in 1:nrow(df)){
    row <- as.integer(df[i,1])
    col <- as.integer(df[i,2])
    rating <- as.numeric(df[i,3])
    rating.df[row,col] <- rating
    #print(paste(paste(row,col),rating))
}

In [21]:
str(rating.df)

 num [1:943, 1:1682] 5 4 0 0 4 4 0 0 0 4 ...


In [22]:
head(rating.df)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] "5"  "3"  "4"  "3"  "3"  "5"  "4"  "1"  "5"  "3"   "⋯"   "0"   "0"   "0"  
[2,] "4"  "0"  "0"  "0"  "0"  "0"  "0"  "0"  "0"  "2"   "⋯"   "0"   "0"   "0"  
[3,] "0"  "0"  "0"  "0"  "0"  "0"  "0"  "0"  "0"  "0"   "⋯"   "0"   "0"   "0"  
[4,] "0"  "0"  "0"  "0"  "0"  "0"  "0"  "0"  "0"  "0"   "⋯"   "0"   "0"   "0"  
[5,] "4"  "3"  "0"  "0"  "0"  "0"  "0"  "0"  "0"  "0"   "⋯"   "0"   "0"   "0"  
[6,] "4"  "0"  "0"  "0"  "0"  "0"  "2"  "4"  "4"  "0"   "⋯"   "0"   "0"   "0"  
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] "0"   "0"   "0"   "0"   "0"   "0"   "0"  
[2,] "0"   "0"   "0"   "0"   "0"   "0"   "0"  
[3,] "0"   "0"   "0"   "0"   "0"   "0"   "0"  
[4,] "0"   "0"   "0"   "0"   "0"   "0"   "0"  
[5,] "0"   "0"   "0"   "0"   "0"   "0"   "0"  
[6,] "0"   "0"   "0"   "0"   "0"   "0"   "0"

In [23]:
tail(rating.df)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
[938,] "4"  "0"  "0"  "0"  "0"  "0"  "4"  "0"  "3"  "0"   "⋯"   "0"   "0"  
[939,] "0"  "0"  "0"  "0"  "0"  "0"  "0"  "0"  "5"  "0"   "⋯"   "0"   "0"  
[940,] "0"  "0"  "0"  "2"  "0"  "0"  "4"  "5"  "3"  "0"   "⋯"   "0"   "0"  
[941,] "5"  "0"  "0"  "0"  "0"  "0"  "4"  "0"  "0"  "0"   "⋯"   "0"   "0"  
[942,] "0"  "0"  "0"  "0"  "0"  "0"  "0"  "0"  "0"  "0"   "⋯"   "0"   "0"  
[943,] "0"  "5"  "0"  "0"  "0"  "0"  "0"  "0"  "3"  "0"   "⋯"   "0"   "0"  
       [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[938,] "0"   "0"   "0"   "0"   "0"   "0"   "0"   "0"  
[939,] "0"   "0"   "0"   "0"   "0"   "0"   "0"   "0"  
[940,] "0"   "0"   "0"   "0"   "0"   "0"   "0"   "0"  
[941,] "0"   "0"   "0"   "0"   "0"   "0"   "0"   "0"  
[942,] "0"   "0"   "0"   "0"   "0"   "0"   "0"   "0"  
[943,] "0"   "0"   "0"   "0"   "0"   "0"   "0"   "0"

In [24]:
rating.df.t <- t(rating.df)

In [25]:
str(rating.df.t)

 num [1:1682, 1:943] 5 3 4 3 3 5 4 1 5 3 ...


In [78]:
recommend.raw.matrix <- rating.df.t %*% rating.df

In [79]:
head(recommend.raw.matrix)

[,1]   [,2]   [,3]  [,4]   [,5]   [,6]  [,7]   [,8]   [,9]   [,10] [,11]
[1,] "7187" "1307" "867" "2051" "774"  "191" "4089" "2486" "2934" "868" "⋯"  
[2,] "1307" "1468" "324" "1024" "389"  "62"  "1141" "787"  "682"  "245" "⋯"  
[3,] "867"  "324"  "959" "535"  "210"  "64"  "897"  "379"  "591"  "183" "⋯"  
[4,] "2051" "1024" "535" "2828" "566"  "93"  "2021" "1589" "1554" "502" "⋯"  
[5,] "774"  "389"  "210" "566"  "1014" "23"  "828"  "503"  "605"  "66"  "⋯"  
[6,] "191"  "62"   "64"  "93"   "23"   "375" "210"  "99"   "204"  "147" "⋯"  
     [,12] [,13] [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] "9"   "0"   "0"   "0"   "9"   "0"   "0"   "0"   "12"  "12" 
[2,] "0"   "0"   "0"   "0"   "0"   "0"   "0"   "0"   "9"   "9"  
[3,] "0"   "0"   "0"   "0"   "3"   "0"   "0"   "0"   "0"   "9"  
[4,] "0"   "0"   "15"  "10"  "6"   "0"   "0"   "0"   "9"   "12" 
[5,] "0"   "0"   "0"   "0"   "0"   "0"   "0"   "0"   "0"   "9"  
[6,] "0"   "0"   "0"   "0"   "0"   "0"   "0"   "0"   "0"   "0"

In [80]:
recommend.raw.matrix.row <- nrow(recommend.raw.matrix);recommend.raw.matrix.row

[1] 1682

## 각 상품별로(row)별로 row(user_id), column(movie), rating 데이터를 recommend matrix에 기록해라

In [88]:
recommend.matrix <- data.frame()

In [89]:
str(recommend.matrix)

'data.frame':	0 obs. of  0 variables


In [90]:
for(i in 1:recommend.raw.matrix.row){
    mat = data.frame("movie_id"=rep(i,recommend.raw.matrix.row),"recommend_id"=1:recommend.raw.matrix.row,
           "score"=t(t(recommend.raw.matrix[i,])))
    recommend.matrix <- rbind(recommend.matrix,mat);
}

In [91]:
head(recommend.matrix)

movie_id recommend_id score
1        1            1  7187
2        1            2  1307
3        1            3   867
4        1            4  2051
5        1            5   774
6        1            6   191

In [122]:
recommend.matrix.df <- tbl_df(recommend.matrix)

find_recommend <- function(id, n){
  res <- select(arrange(filter(recommend.matrix.df,movie_id == id,
                        recommend_id != id),desc(score)),movie_id,recommend_id,score)[1:n,]
  return(as.data.frame(res))
}

In [123]:
select(arrange(filter(recommend.matrix.df,movie_id == 1,
                        recommend_id != 1),desc(score)),movie_id,recommend_id,score)[1:30,]

Source: local data frame [30 x 3]

   movie_id recommend_id score
      (int)        (int) (dbl)
1         1           50  6686
2         1          181  5495
3         1          100  5143
4         1          174  4698
5         1          121  4378
6         1           98  4202
7         1          117  4185
8         1          172  4180
9         1          127  4165
10        1            7  4089
..      ...          ...   ...

In [124]:
find_recommend(1,30)

movie_id recommend_id score
1         1           50  6686
2         1          181  5495
3         1          100  5143
4         1          174  4698
5         1          121  4378
6         1           98  4202
7         1          117  4185
8         1          172  4180
9         1          127  4165
10        1            7  4089
11        1          237  3968
12        1          222  3894
13        1           56  3875
14        1          258  3731
15        1           79  3711
16        1          173  3709
17        1          151  3705
18        1          204  3675
19        1          168  3563
20        1           69  3541
21        1          210  3541
22        1          405  3483
23        1          318  3474
24        1           64  3432
25        1          257  3368
26        1           28  3351
27        1           96  3324
28        1          195  3317
29        1          294  3316
30        1           22  3282

In [97]:
movie_title_raw <- read.csv(file="./ml-100k/u.item",sep="|",header=FALSE)

In [100]:
movie_title <- movie_title_raw[,1:2]

In [101]:
head(movie_title)

V1                                                   V2
1  1                                     Toy Story (1995)
2  2                                     GoldenEye (1995)
3  3                                    Four Rooms (1995)
4  4                                    Get Shorty (1995)
5  5                                       Copycat (1995)
6  6 Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)

In [103]:
colnames(movie_title) <- c("movie_id","title")

In [125]:
find_recommend2 <- function(id, n){
  res <- select(arrange(filter(recommend.matrix.df,movie_id == id,
                        recommend_id != id),desc(score)),recommend_id,score)[1:n,]
  res.df <- as.data.frame(res)
  colnames(res.df) <- c("movie_id","score")  
  res.df <- merge(res.df,movie_title,by="movie_id")  
  return(res.df)
}

In [128]:
movie_title[567,]

movie_id                             title
567      567 Wes Craven's New Nightmare (1994)

In [129]:
find_recommend2(567,30)

movie_id score                             title
1         7   361             Twelve Monkeys (1995)
2        11   243              Seven (Se7en) (1995)
3        12   258        Usual Suspects, The (1995)
4        28   234                  Apollo 13 (1995)
5        50   382                  Star Wars (1977)
6        53   237       Natural Born Killers (1994)
7        56   346               Pulp Fiction (1994)
8        96   284 Terminator 2: Judgment Day (1991)
9        98   375  Silence of the Lambs, The (1991)
10      100   362                      Fargo (1996)
11      127   236             Godfather, The (1972)
12      172   277   Empire Strikes Back, The (1980)
13      173   249        Princess Bride, The (1987)
14      174   298    Raiders of the Lost Ark (1981)
15      176   278                     Aliens (1986)
16      181   322         Return of the Jedi (1983)
17      183   287                      Alien (1979)
18      184   287           Army of Darkness (1993)
19      185   321                     Psycho (1960)
20      195   257            Terminator, The (1984)
21      200   346               Shining, The (1980)
22      201   237               Evil Dead II (1987)
23      218   290                  Cape Fear (1991)
24      219   316 Nightmare on Elm Street, A (1984)
25      234   343                       Jaws (1975)
26      258   241                    Contact (1997)
27      288   352                     Scream (1996)
28      447   256                     Carrie (1976)
29      448   247                  Omen, The (1976)
30      568   244                      Speed (1994)